<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>lemon_reach</name>
  <version>0.1.0</version>
  <description>Single-shot MoveIt approach to the largest detected Lemon, using yolo_ros 3D detections.</description>
  <maintainer email="mhieda.robotics@gmail.com">hidayat</maintainer>
  <license>Apache-2.0</license>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <depend>rclpy</depend>
  <depend>std_srvs</depend>
  <depend>std_msgs</depend>
  <depend>python3-numpy</depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>yolo_bringup</exec_depend>
  <exec_depend>lemon_grasp</exec_depend>
  <exec_depend>moveit_configs_utils</exec_depend>
  <exec_depend>piper_with_gripper_moveit</exec_depend>
  <depend>geometry_msgs</depend>
  <depend>shape_msgs</depend>
  <depend>moveit_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>sensor_msgs_py</depend>
  <depend>yolo_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>lemon_msgs</depend>
  <depend>visualization_msgs</depend>
  <exec_depend>python3-opencv</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
